-   active_time:
        -   start: "2016-01-02T00:00:00+08:00"
            end: "2016-08-02T15:00:00+08:00"
    id: 1
    platform:
        - 1
        - 101
    include_location:
        - 1156130000
        - 1156610000
        - 1156430100
            
    include_tag:
        - 1000101
          #- 34234
    creative:
        -   id: 101
            url: "http://test.com.dd"
            height: 340
            width: 280
            type: 2
            duration: 15
            landing_page : "http://landing.page.com"    
    click_url:
        - "http://test.click.com/click1"
        - "http://test.click.com/click2"
    monitor_url:
        -   event: 1
            url: "http://test.click.com/impression1?imei=__IMEI__&ip=__IP__"
        -   event: 2
            url: "http://test.click.com/impression2?imei=__IMEI__&ip=__IP__"
    max_price: 2100
    flow:
        -   type: 1
            speed: 1
            num: 86400
    frequency:
        -   type: 0
            num: 2
        -   type: 1
            num: 7
